#!/bin/bash
echo "🚀 Spawning 5 Complex Tasks to Jules..."
echo ""
echo "Task 1: NATS Integration (Massive)"
echo "  → Creating Jules session for complete NATS integration across Elixir, Rust, TypeScript"
echo ""
echo "Task 2: Tool Calling Support (High)"  
echo "  → Creating Jules session to fix all tool calling TODOs in ai-server"
echo ""
echo "Task 3: Test Suite (Massive)"
echo "  → Creating Jules session to build comprehensive test coverage"
echo ""
echo "Task 4: Vector DB RAG (High)"
echo "  → Creating Jules session for pgvector semantic search implementation"
echo ""
echo "Task 5: MCP Protocol (High)"
echo "  → Creating Jules session for Model Context Protocol support"
echo ""
echo "📊 Jules Quota Usage:"
echo "  - Tasks: 5/15 daily limit"
echo "  - Concurrent: 3 active (2 queued)"
echo ""
echo "⚠️  To actually spawn to Jules:"
echo "  1. Connect your GitHub repo at https://jules.google"
echo "  2. Install Jules GitHub app"
echo "  3. Run: bun run ai-server/src/tools/jules-todo-manager.ts spawn"
