type: 'library'
language: 'rust'

project:
  name: '@singularity/embedding_engine'
  description: 'GPU-accelerated embedding generation with Qodo-Embed-1 and Jina v3'

tags: ['rust', 'nif', 'embeddings', 'gpu', 'ml']

dependsOn:
  # No internal deps - standalone Rustler NIF

fileGroups:
  sources:
    - 'src/**/*'
    - 'Cargo.toml'
  tests:
    - 'tests/**/*'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
      - '@globs(sources)'
    outputs:
      - 'target/release/libembedding_engine.so'

  test:
    command: 'cargo test'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'

  clippy:
    command: 'cargo clippy -- -D warnings'
    inputs:
      - '@globs(sources)'

  fmt:
    command: 'cargo fmt --check'
    inputs:
      - '@globs(sources)'

  bench:
    command: 'cargo bench'
    inputs:
      - '@globs(sources)'
      - 'benches/**/*'
