name: Code Quality Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Singularity Scanner
      run: |
        curl -fsSL https://get.singularity.dev/install.sh | bash
        echo "$HOME/.singularity/bin" >> $GITHUB_PATH

    - name: Run Singularity Code Quality Analysis
      env:
        SINGULARITY_API_KEY: ${{ secrets.SINGULARITY_API_KEY }}
        SINGULARITY_API_ENDPOINT: ${{ secrets.SINGULARITY_API_ENDPOINT }}
      run: |
        singularity-scan

    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { exec } = require('child_process');
          const { promisify } = require('util');
          const execAsync = promisify(exec);

          try {
            const { stdout } = await execAsync('singularity-scan --json');
            const results = JSON.parse(stdout);

            const comment = `
            ## ðŸ” Singularity Code Quality Analysis

            **Quality Score:** ${results.quality_score}/10
            **Issues Found:** ${results.issues_count}
            **Recommendations:** ${results.recommendations.length}

            ### Top Recommendations:
            ${results.recommendations.slice(0, 3).map(r => `- ${r.message}`).join('\n')}

            [View full report](https://app.singularity.dev/repos/${{ github.repository }}/analysis/${{ github.sha }})
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } catch (error) {
            console.log('Analysis comment failed:', error.message);
          }