type: 'library'
language: 'rust'

project:
  name: '@singularity/linting_engine'
  description: 'Multi-language linting engine'

tags: ['rust', 'linting', 'quality']

dependsOn:
  - 'rust/universal_parser'

fileGroups:
  sources:
    - 'src/**/*'
    - 'Cargo.toml'
  tests:
    - 'tests/**/*'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
      - '@globs(sources)'
    outputs:
      - 'target/release/liblinting_engine.a'

  test:
    command: 'cargo test'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'

  clippy:
    command: 'cargo clippy -- -D warnings'
    inputs:
      - '@globs(sources)'
