defmodule Mix.Tasks.Template.Upgrade do
  @moduledoc """
  Upgrade code generated from evolved templates.

  ## Usage

      # Upgrade all files from a template
      mix template.upgrade quality_template:elixir-genserver --to 2.0.0

      # Upgrade from specific version
      mix template.upgrade quality_template:elixir-genserver --from 1.0.0 --to 2.0.0

      # Upgrade single file
      mix template.upgrade --file lib/my_app/worker.ex --to 2.0.0

      # Dry run (show what would be done)
      mix template.upgrade quality_template:elixir-genserver --to 2.0.0 --dry-run

  ## What it does

  1. Finds all files generated by the template
  2. Runs "before" migration scripts (renames, backups, etc.)
  3. Regenerates code with new template version
  4. Runs "after" migration scripts (format, test, etc.)
  5. Records successful migrations in database

  ## Migration Safety

  - Always backup files before migration
  - Validate new code compiles before replacing
  - Track migration success/failure for debugging
  - Rollback on error (if backup exists)
  """

  use Mix.Task

  alias Singularity.Knowledge.TemplateMigration

  @shortdoc "Upgrade code from evolved templates"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {opts, args, _} =
      OptionParser.parse(args,
        strict: [
          from: :string,
          to: :string,
          file: :string,
          dry_run: :boolean
        ]
      )

    template_id = List.first(args)
    to_version = Keyword.get(opts, :to)
    from_version = Keyword.get(opts, :from)
    file_path = Keyword.get(opts, :file)
    dry_run = Keyword.get(opts, :dry_run, false)

    cond do
      file_path && to_version ->
        upgrade_file(file_path, to_version, dry_run)

      template_id && to_version ->
        upgrade_template(template_id, from_version, to_version, dry_run)

      true ->
        Mix.shell().error("""
        Usage:
          mix template.upgrade <template_id> --to <version> [--from <version>]
          mix template.upgrade --file <path> --to <version>

        Examples:
          mix template.upgrade quality_template:elixir-genserver --to 2.0.0
          mix template.upgrade --file lib/my_app/worker.ex --to 2.0.0
        """)

        exit({:shutdown, 1})
    end
  end

  defp upgrade_template(template_id, from_version, to_version, dry_run) do
    Mix.shell().info("Upgrading #{template_id} to version #{to_version}...")

    if from_version do
      Mix.shell().info("From version: #{from_version}")
    end

    if dry_run do
      Mix.shell().info("DRY RUN - no changes will be made")
    end

    case TemplateMigration.upgrade_template(
           template_id: template_id,
           from_version: from_version,
           to_version: to_version
         ) do
      {:ok, %{success: success, total: total, results: results}} ->
        Mix.shell().info("\nMigration Results:")
        Mix.shell().info("  Success: #{success}/#{total}")

        failed = Enum.filter(results, &match?({:error, _}, &1))

        if length(failed) > 0 do
          Mix.shell().error("\nFailed migrations:")

          Enum.each(failed, fn {:error, reason} ->
            Mix.shell().error("  - #{inspect(reason)}")
          end)
        end

        if success == total do
          Mix.shell().info("\n✓ All migrations successful!")
        else
          Mix.shell().error("\n✗ Some migrations failed - review errors above")
          exit({:shutdown, 1})
        end

      {:error, reason} ->
        Mix.shell().error("Migration failed: #{inspect(reason)}")
        exit({:shutdown, 1})
    end
  end

  defp upgrade_file(file_path, to_version, dry_run) do
    Mix.shell().info("Upgrading #{file_path} to version #{to_version}...")

    if dry_run do
      Mix.shell().info("DRY RUN - no changes will be made")
    end

    case TemplateMigration.migrate_file(file_path: file_path, to_version: to_version) do
      {:ok, _} ->
        Mix.shell().info("✓ Migration successful!")

      {:error, reason} ->
        Mix.shell().error("✗ Migration failed: #{inspect(reason)}")
        exit({:shutdown, 1})
    end
  end
end
