$schema: 'https://moonrepo.dev/schemas/project.json'

language: 'rust'
type: 'library'

project:
  name: 'knowledge_intelligence'
  description: 'Knowledge intelligence NIF for Elixir'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
      - 'Cargo.toml'
      - 'src/**/*'
    outputs:
      - 'target/release/libknowledge_intelligence.{so,dylib,dll}'

  test:
    command: 'cargo test'
    inputs:
      - 'Cargo.toml'
      - 'src/**/*'
      - 'tests/**/*'
