type: 'library'
language: 'rust'

project:
  name: '@singularity/tool_doc_index'
  description: 'Tool documentation indexer and template collector'

tags: ['rust', 'indexing', 'templates', 'documentation']

fileGroups:
  sources:
    - 'src/**/*'
    - 'Cargo.toml'
  tests:
    - 'tests/**/*'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
      - '@globs(sources)'
    outputs:
      - 'target/release/tool_doc_index'

  test:
    command: 'cargo test'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'

  clippy:
    command: 'cargo clippy -- -D warnings'
    inputs:
      - '@globs(sources)'
