defmodule Singularity.Metrics.AggregatedData do
  @moduledoc """
  Metrics Aggregated Data Schema - Time-bucketed statistics.

  Stores pre-computed statistics (count, sum, avg, min, max, stddev) for
  metric events aggregated over hourly or daily periods.

  Generated by EventAggregator.aggregate_by_period/2 and consumed by Query API.

  ## Module Identity (JSON)

  ```json
  {
    "module": "Singularity.Metrics.AggregatedData",
    "purpose": "Time-series statistics for metrics (hourly/daily rollups)",
    "layer": "metrics",
    "status": "production",
    "table": "metrics_aggregated"
  }
  ```

  ## Fields

  - `event_name` - Event identifier (same as Event.event_name)
  - `period` - Aggregation period: "hour" or "day"
  - `period_start` - Start of the aggregation period (UTC)
  - `count` - Number of events in period
  - `sum` - Sum of all measurements
  - `avg` - Average (sum / count)
  - `min` - Minimum measurement value
  - `max` - Maximum measurement value
  - `stddev` - Standard deviation (optional)
  - `tags` - JSONB map of tag filters used for this aggregation

  ## Example Aggregations

  ```
  {
    event_name: "llm.cost",
    period: "hour",
    period_start: "2025-10-24T13:00:00Z",
    count: 42,
    sum: 1.25,
    avg: 0.0298,
    min: 0.01,
    max: 0.08,
    tags: {model: "claude-opus"}
  }

  {
    event_name: "agent.success",
    period: "day",
    period_start: "2025-10-24T00:00:00Z",
    count: 1024,
    sum: 1018,
    avg: 0.994,
    min: 0,
    max: 1,
    stddev: 0.024
  }
  ```

  ## Uniqueness

  Unique constraint ensures no duplicate aggregations:
  - (event_name, period, period_start, tags)

  This allows idempotent re-aggregation without creating duplicates.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "metrics_aggregated" do
    field :event_name, :string
    field :period, :string  # "hour" or "day"
    field :period_start, :utc_datetime_usec

    # Statistics
    field :count, :integer
    field :sum, :float
    field :avg, :float
    field :min, :float
    field :max, :float
    field :stddev, :float

    # Tag filters used for this aggregation
    field :tags, :map, default: %{}

    timestamps(type: :utc_datetime_usec)
  end

  @doc false
  def changeset(data, attrs) do
    data
    |> cast(attrs, [:event_name, :period, :period_start, :count, :sum, :avg, :min, :max, :stddev, :tags])
    |> validate_required([:event_name, :period, :period_start, :count])
    |> validate_inclusion(:period, ["hour", "day"])
    |> validate_statistics()
    |> unique_constraint(:event_name_period_start_tags,
      name: "metrics_aggregated_unique_idx",
      message: "Already aggregated for this period"
    )
  end

  @doc """
  Validate that statistics make sense (count > 0, sum >= count * min, etc.)
  """
  defp validate_statistics(changeset) do
    validate_change(changeset, :count, fn :count, count ->
      if count > 0 do
        []
      else
        [:count, "must be greater than 0"]
      end
    end)
  end
end
