type: 'library'
language: 'rust'

project:
  name: '@singularity/code_engine'
  description: 'Code analysis suite with quality detection and metrics'

tags: ['rust', 'analysis', 'quality', 'linting']

dependsOn:
  - 'rust/universal_parser'

fileGroups:
  sources:
    - 'src/**/*'
    - 'Cargo.toml'
  tests:
    - 'tests/**/*'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
      - '@globs(sources)'
    outputs:
  - 'target/release/libcode_engine.a'

  test:
    command: 'cargo test'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'

  clippy:
    command: 'cargo clippy -- -D warnings'
    inputs:
      - '@globs(sources)'
