#!/usr/bin/env bash
# Bundle AI Provider Credentials for Deployment
# This script extracts all authentication credentials and creates a .env file

set -e

OUTPUT_FILE="${1:-.env.ai-providers}"

echo "🔐 Bundling AI Provider Credentials..."
echo ""

# Initialize output file
cat > "$OUTPUT_FILE" << 'EOF'
# AI Providers Authentication Credentials
# Generated by bundle-credentials.sh
# DO NOT COMMIT TO GIT

EOF

# Function to check if file exists
check_file() {
    if [ ! -f "$1" ]; then
        echo "⚠️  Warning: $1 not found"
        return 1
    fi
    return 0
}

# Gemini ADC
echo "📦 Bundling Gemini ADC credentials..."
GCLOUD_CREDS="$HOME/.config/gcloud/application_default_credentials.json"
if check_file "$GCLOUD_CREDS"; then
    echo "GOOGLE_APPLICATION_CREDENTIALS_JSON=$(cat "$GCLOUD_CREDS" | base64 -w 0)" >> "$OUTPUT_FILE"
    echo "✓ Gemini ADC bundled"
else
    echo "  Run: gcloud auth application-default login"
fi
echo ""

# Claude long-term token
echo "📦 Bundling Claude credentials..."
CLAUDE_CREDS="$HOME/.claude/.credentials.json"
if check_file "$CLAUDE_CREDS"; then
    CLAUDE_TOKEN=$(jq -r '.claudeAiOauth.accessToken' "$CLAUDE_CREDS")
    echo "CLAUDE_ACCESS_TOKEN=$CLAUDE_TOKEN" >> "$OUTPUT_FILE"
    echo "✓ Claude token bundled"
else
    echo "  Run: claude setup-token"
fi
echo ""

# Cursor OAuth
echo "📦 Bundling Cursor credentials..."
CURSOR_CREDS="$HOME/.config/cursor/auth.json"
if check_file "$CURSOR_CREDS"; then
    echo "CURSOR_AUTH_JSON=$(cat "$CURSOR_CREDS" | base64 -w 0)" >> "$OUTPUT_FILE"
    echo "✓ Cursor OAuth bundled"
else
    echo "  Run: cursor-agent login"
fi
echo ""

# GitHub Token
echo "📦 Bundling GitHub token..."
if command -v gh &> /dev/null; then
    GH_TOKEN=$(gh auth token 2>/dev/null || echo "")
    if [ -n "$GH_TOKEN" ]; then
        echo "GH_TOKEN=$GH_TOKEN" >> "$OUTPUT_FILE"
        echo "✓ GitHub token bundled"
    else
        echo "⚠️  Warning: GitHub token not found"
        echo "  Run: gh auth login"
    fi
else
    echo "⚠️  Warning: gh CLI not installed"
    echo "  Manually add: GH_TOKEN=your_token_here"
fi
echo ""

# Gemini Code Project
echo "📦 Adding Gemini Code project..."
echo "GEMINI_CODE_PROJECT=gemini-code-473918" >> "$OUTPUT_FILE"
echo "✓ Gemini Code project added"
echo ""

# Port
echo "📦 Adding default port..."
echo "PORT=3000" >> "$OUTPUT_FILE"
echo "✓ Port added"
echo ""

echo "✅ Credentials bundled to: $OUTPUT_FILE"
echo ""
echo "⚠️  IMPORTANT SECURITY NOTES:"
echo "  1. Add $OUTPUT_FILE to .gitignore"
echo "  2. Keep this file secure and encrypted"
echo "  3. Rotate credentials regularly"
echo ""
echo "📝 Next steps:"
echo "  1. Review $OUTPUT_FILE"
echo "  2. Deploy with: source $OUTPUT_FILE && bun run ai:server"
echo "  3. Or use with Docker: docker run --env-file $OUTPUT_FILE ai-server"
echo ""
